name: client
description: Community portal frontend
repository: https://github.com/openfoodfacts/community-portal
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO Remove this dependency
  cupertino_icons: ^1.0.5
  responsive_builder: ^0.4.2
  flutter_svg: ^1.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git

flutter:
  uses-material-design: true
