# Generated by Django 4.0.5 on 2022-07-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='cover_image',
            new_name='thumbnail',
        ),
    ]
